services:
  mysql:
    image: mysql:8.4.0
    cap_add:
      - SYS_NICE
    container_name: "db-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
    env_file:
    - .env
    environment:
      DB_DSN: "root:${MYSQL_ROOT_PASSWORD}@tcp(db-mysql:3306)/${MYSQL_DATABASE}"
      KAFKA_BROKER: "kafka:9092"
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

volumes:
  db:
    driver: local
